server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: xima-app
  
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/xima?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # Redis配置
  redis:
    host: localhost
    port: 6379
    database: 0
  
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xima.app.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

# JWT配置
jwt:
  secret: xima_chat_application_jwt_secret_key_should_be_longer_in_production
  expiration: 86400000  # 1天，单位：毫秒

# 文件存储配置
file:
  upload-dir: ./uploads/

# 日志配置
logging:
  level:
    root: INFO
    com.xima: DEBUG
    org.springframework.web: INFO 